title: York Computer
description: Managed IT services and cybersecurity for small businesses and homes in York, PA. Your Digital Bodyguard.
url: "https://yorkcomputer.net"
baseurl: ""
permalink: /blog/:title.html

defaults:
  - scope:
      path: ""
    values:
      layout: default
